import type { Metadata } from "next";
import { Inter } from "next/font/google";
import '@gravity-ui/uikit/styles/fonts.css';
import '@gravity-ui/uikit/styles/styles.css';
import MainProvider from "@/src/providers/MainProvider";
import Navbar from "@/src/components/Navbar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Cargo",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={'g-root g-root_theme_light'}>
        <MainProvider>
          <Navbar/>
          {children}
        </MainProvider>
      </body>
    </html>
  );
}
